name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: valitydev/action-tagger@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          with-v: true
